name: cookify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  provider: ^6.1.5+1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/splash_images/
    - assets/images/home_images/
    - assets/images/home_images/asian/
    - assets/images/home_images/chinese/
    - assets/images/home_images/italian/
    - assets/images/home_images/pakistani/
  