name: eventify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_logo.png
  android_12:
    image: assets/app_logo.png
    color: "#ffffff"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/concert_images/
    - assets/images/tech_images/
    - assets/images/other_event_images/

